import type { Agent, SkillNode, CareerRole, DashboardMetrics } from "@/types";

export const AGENTS: Agent[] = [
  {
    id: "orchestrator",
    name: "Orchestrator",
    role: "任务编排 · 总指挥",
    status: "active",
    x: 50,
    y: 50,
    connections: ["researcher", "coder", "analyst", "planner"],
    icon: "◈",
    description: "中央协调器，负责任务分配、工作流编排与全局状态管理",
    metrics: { tasksCompleted: 12480, accuracy: 99.7, latency: 12 },
  },
  {
    id: "researcher",
    name: "Deep Research",
    role: "深度研究 · 知识挖掘",
    status: "processing",
    x: 25,
    y: 30,
    connections: ["orchestrator", "analyst", "coder"],
    icon: "◎",
    description: "多源信息检索、知识图谱构建与深度研究分析",
    metrics: { tasksCompleted: 8920, accuracy: 98.5, latency: 45 },
  },
  {
    id: "coder",
    name: "Code Architect",
    role: "架构编程 · 自动开发",
    status: "active",
    x: 75,
    y: 30,
    connections: ["orchestrator", "reviewer", "researcher"],
    icon: "◇",
    description: "全栈代码生成、架构设计、自动化测试与部署",
    metrics: { tasksCompleted: 15600, accuracy: 97.2, latency: 28 },
  },
  {
    id: "analyst",
    name: "Data Oracle",
    role: "数据分析 · 洞察引擎",
    status: "idle",
    x: 20,
    y: 70,
    connections: ["orchestrator", "researcher", "planner"],
    icon: "△",
    description: "大规模数据挖掘、趋势预测、异常检测与商业智能",
    metrics: { tasksCompleted: 7200, accuracy: 99.1, latency: 35 },
  },
  {
    id: "planner",
    name: "Strategist",
    role: "战略规划 · 决策辅助",
    status: "active",
    x: 80,
    y: 70,
    connections: ["orchestrator", "analyst", "reviewer"],
    icon: "▽",
    description: "多维度决策分析、资源优化配置与战略路线图规划",
    metrics: { tasksCompleted: 5400, accuracy: 96.8, latency: 22 },
  },
  {
    id: "reviewer",
    name: "Quality Sentinel",
    role: "质量守护 · 安全审查",
    status: "active",
    x: 50,
    y: 85,
    connections: ["coder", "planner", "orchestrator"],
    icon: "▣",
    description: "代码审查、安全审计、合规检查与质量标准管控",
    metrics: { tasksCompleted: 9800, accuracy: 99.4, latency: 18 },
  },
];

export const SKILL_TREE: SkillNode[] = [
  { id: "frontend", name: "Frontend AI", category: "engineering", level: 1, progress: 85, x: 30, y: 15, prerequisites: [], unlocked: true, icon: "⬡", energy: 0.9 },
  { id: "llm", name: "LLM Engineering", category: "core", level: 1, progress: 92, x: 50, y: 10, prerequisites: [], unlocked: true, icon: "⬡", energy: 0.95 },
  { id: "prompt", name: "Prompt Engineering", category: "core", level: 1, progress: 95, x: 70, y: 15, prerequisites: ["llm"], unlocked: true, icon: "⬡", energy: 0.98 },
  { id: "rag", name: "RAG Systems", category: "core", level: 2, progress: 78, x: 45, y: 30, prerequisites: ["llm", "prompt"], unlocked: true, icon: "⬡", energy: 0.8 },
  { id: "multi_agent", name: "Multi-Agent", category: "engineering", level: 2, progress: 70, x: 65, y: 30, prerequisites: ["prompt", "llm"], unlocked: true, icon: "⬡", energy: 0.75 },
  { id: "automation", name: "AI Automation", category: "engineering", level: 2, progress: 88, x: 25, y: 35, prerequisites: ["frontend"], unlocked: true, icon: "⬡", energy: 0.88 },
  { id: "vision", name: "Computer Vision", category: "ai", level: 2, progress: 60, x: 85, y: 35, prerequisites: ["prompt"], unlocked: true, icon: "⬡", energy: 0.65 },
  { id: "infra", name: "AI Infrastructure", category: "engineering", level: 3, progress: 55, x: 35, y: 50, prerequisites: ["rag", "multi_agent"], unlocked: false, icon: "⬡", energy: 0.55 },
  { id: "product", name: "AI Product", category: "business", level: 3, progress: 72, x: 55, y: 50, prerequisites: ["multi_agent", "rag"], unlocked: true, icon: "⬡", energy: 0.72 },
  { id: "blockchain", name: "Blockchain AI", category: "frontier", level: 3, progress: 40, x: 75, y: 50, prerequisites: ["vision", "infra"], unlocked: false, icon: "⬡", energy: 0.4 },
  { id: "decision", name: "AI Decision Sys", category: "business", level: 4, progress: 50, x: 45, y: 70, prerequisites: ["product", "infra"], unlocked: false, icon: "⬡", energy: 0.5 },
  { id: "civilization", name: "Digital Civilization", category: "frontier", level: 4, progress: 30, x: 65, y: 70, prerequisites: ["blockchain", "product"], unlocked: false, icon: "⬡", energy: 0.3 },
];

export const CAREER_GALAXY: CareerRole[] = [
  { id: "mle", title: "ML Engineer", category: "Core AI", demand: 95, salary: { min: 150000, max: 350000, currency: "USD" }, skills: ["Python", "PyTorch", "Transformer"], orbit: 1, angle: 0, growth: 35, companies: ["OpenAI", "Google", "Meta"] },
  { id: "agent_eng", title: "Agent Engineer", category: "AI Agent", demand: 98, salary: { min: 160000, max: 380000, currency: "USD" }, skills: ["LangChain", "Multi-Agent", "RAG"], orbit: 1, angle: 45, growth: 48, companies: ["Anthropic", "Microsoft", "Startups"] },
  { id: "prompt_eng", title: "Prompt Architect", category: "AI Interaction", demand: 88, salary: { min: 130000, max: 280000, currency: "USD" }, skills: ["Prompt Design", "Chain-of-Thought", "Eval"], orbit: 1, angle: 90, growth: 30, companies: ["OpenAI", "Cohere", "AI21"] },
  { id: "ai_pm", title: "AI Product Lead", category: "Product", demand: 92, salary: { min: 170000, max: 400000, currency: "USD" }, skills: ["AI Strategy", "UX Research", "GTM"], orbit: 1, angle: 135, growth: 42, companies: ["Google", "Apple", "Amazon"] },
  { id: "rag_eng", title: "RAG Engineer", category: "AI Infra", demand: 85, salary: { min: 145000, max: 320000, currency: "USD" }, skills: ["Vector DB", "Embeddings", "Knowledge Graph"], orbit: 2, angle: 22, growth: 38, companies: ["Pinecone", "Weaviate", "Elastic"] },
  { id: "vision_eng", title: "Vision AI Eng", category: "Perception", demand: 82, salary: { min: 140000, max: 310000, currency: "USD" }, skills: ["CV", "Diffusion", "NeRF"], orbit: 2, angle: 67, growth: 28, companies: ["Tesla", "NVIDIA", "Waymo"] },
  { id: "ai_sec", title: "AI Security Eng", category: "Security", demand: 90, salary: { min: 155000, max: 360000, currency: "USD" }, skills: ["Adversarial ML", "Alignment", "Red Teaming"], orbit: 2, angle: 112, growth: 44, companies: ["Anthropic", "OpenAI", "Palantir"] },
  { id: "ai_arch", title: "AI Architect", category: "Engineering", demand: 94, salary: { min: 180000, max: 450000, currency: "USD" }, skills: ["System Design", "Scale", "Orchestration"], orbit: 2, angle: 157, growth: 36, companies: ["Stripe", "Netflix", "Uber"] },
  { id: "ai_ethics", title: "AI Ethicist", category: "Governance", demand: 75, salary: { min: 120000, max: 250000, currency: "USD" }, skills: ["Policy", "Fairness", "Transparency"], orbit: 3, angle: 10, growth: 32, companies: ["EU Commission", "UN", "Think Tanks"] },
  { id: "robotics_ai", title: "Robotics AI", category: "Embodied AI", demand: 80, salary: { min: 135000, max: 300000, currency: "USD" }, skills: ["ROS", "Sim-to-Real", "RL"], orbit: 3, angle: 55, growth: 40, companies: ["Boston Dynamics", "Tesla", "Figure"] },
  { id: "ai_edu", title: "AI Educator", category: "Education", demand: 70, salary: { min: 100000, max: 220000, currency: "USD" }, skills: ["Pedagogy", "AI Literacy", "Content"], orbit: 3, angle: 100, growth: 25, companies: ["Coursera", "Udacity", "DeepLearning"] },
  { id: "agi_res", title: "AGI Researcher", category: "Frontier", demand: 78, salary: { min: 200000, max: 500000, currency: "USD" }, skills: ["Theory", "Alignment", "Cognitive Arch"], orbit: 3, angle: 145, growth: 50, companies: ["DeepMind", "OpenAI", "Anthropic"] },
];

export const DASHBOARD_METRICS: DashboardMetrics = {
  activeAgents: 47,
  tasksInQueue: 1283,
  completedToday: 9420,
  systemHealth: 99.8,
  tokenUsage: 2847500,
  avgResponseTime: 142,
  successRate: 99.4,
  uptime: 99.99,
};

export const TASK_DISTRIBUTION = [
  { time: "00:00", value: 420, label: "代码生成" },
  { time: "02:00", value: 380, label: "数据分析" },
  { time: "04:00", value: 290, label: "文档处理" },
  { time: "06:00", value: 510, label: "知识检索" },
  { time: "08:00", value: 680, label: "任务编排" },
  { time: "10:00", value: 920, label: "智能决策" },
  { time: "12:00", value: 850, label: "安全审查" },
  { time: "14:00", value: 780, label: "代码生成" },
  { time: "16:00", value: 950, label: "数据分析" },
  { time: "18:00", value: 710, label: "文档处理" },
  { time: "20:00", value: 540, label: "知识检索" },
  { time: "22:00", value: 460, label: "任务编排" },
];